### ISSUE TITLE
Accept tables as "lists"

### ISSUE THREAD

**Issue by kylef** [clayallsopp/readme-score#3]
There is a scoreboard for 0-10 for "Has any lists?". I think it would make sense to add another score for tables or accept tables as lists.

Example: https://github.com/QueryKit/QueryKit#operators

**Comment by clayallsopp** [comment]
Totally, tables are handy (and probably worth slightly more than a list). would love a PR for it!

**Comment by kylef** [comment]
I have no interest or time to work on this anymore and it's old. Closing.
